version: "3.1"

services:
  joomla:
    depends_on:
      - joomladb
    container_name: joomla
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: example
      JOOMLA_DB_PASSWORD: example
      JOOMLA_DB_NAME: example
    volumes:
      - ./joomla:/var/www/html

  joomladb:
    image: mysql:8.0
    container_name: joomladb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - joomladb:/var/lib/mysql

volumes:
  joomladb:
